# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  clean:
    desc: Clean the generated files
    cmds:
      - cmd: |-
          set +e
          rm -r ./result/
          rm ./result/
          rm ./nixos.qcow2
  run-image:
    desc: Run the generated NixOS image inside QEMU.
    deps:
      - task: build-vm-image
        vars:
          HOST_NAME: "gnome"
    cmds:
      - QEMU_KERNEL_PARAMS=console=ttyS0 ./result/bin/run-nixos-vm
  build-iso-image:
    label: build-iso-image-{{.HOST_NAME}}
    desc: Build the NixOS ISO image.
    requires:
      vars:
        - name: HOST_NAME
          enum: ["simple", "gnome"]
    sources:
      - ./hosts/{{.HOST_NAME}}/**
    generates:
      - ./result/iso/*.iso
    cmds:
      # - nixos-rebuild build-image --show-trace --image-variant iso --flake .#{{.HOST_NAME}}
      - nix build .#nixosConfigurations.{{.HOST_NAME}}.config.system.build.images.iso
  build-vm-image:
    label: build-vm-image-{{.HOST_NAME}}
    vars:
      HOST_NAME: '{{default "default" .HOST_NAME}}'
    desc: Build the NixOS image for VM.
    sources:
      - ./hosts/{{.HOST_NAME}}/**
    generates:
      - ./result/bin/run-nixos-vm
    cmds:
      - nix-build '<nixpkgs/nixos>' -A vm -I nixpkgs=channel:nixos-25.11 -I nixos-config=./hosts/{{.HOST_NAME}}/configuration.nix
